### ISSUE TITLE
No 'install' informations available

### ISSUE THREAD

**Issue by RaimundWege** [raeleus/skin-composer#6] opened 2016-08-11 06:45 UTC
If you start the desktop project in android studio on a mac you ran into some problems:
1. You have to go to 'File/Project Structure...' and set the project language level to '8 - Lambdas, type annotations etc.'
2. In build.gradle you have to set: visuiVersion = '1.1.6-SNAPSHOT'
3. The line: 'config.setWindowSizeLimits(675, 400, -1, -1);' in DesktopLauncher throws NoSuchMethodError (no idea why). So this line needs to be commented out.
4. You have to start the project with the vm option: -XstartOnFirstThread
5. Enjoy!

Eventually you should always ship a compiled version in master branch :)

(Your C64 skin is great!)

**Comment by raeleus** [comment] 2016-08-11 18:26
Thanks for posting this. I don't have a Mac and do most of my programming in the Netbeans IDE so this is very helpful.
1. This is directly related to my choice in using a newer Java version to make it compatible with the Windows dialog. At this point it would involve a lot of work to roll back, but I'll keep it in mind.
2. Yeah, I need to change that as that snapshot isn't valid anymore.
3. I thought this was related to a LWJGL3 error that was already fixed. I'll investigate.
4. I'm not familiar with this at all so I'll have to do some research.

I'm not at all used to how people do releases on GitHub. I did make a "release" with precompiled versions https://github.com/raeleus/skin-composer/releases
Though I'll add them to the main branch too. Thanks for the compliments. I'll focus on this as soon as I clear up my workload.

**Comment by hermangh** [comment] 2017-02-13 03:50
I'm Mac and tried the version 7 and 8 executables and have no luck. The app just started and exited without any error messages. I obtained the executables by download the skin_compose_mac and then unzip the skin-composer-app-install.zip. What else I need to do before I can successfully start up the skin composer? Thanks in advance.

**Comment by raeleus** [comment] 2017-02-13 04:05
I don't have a mac to test so I'm really in the dark here. The skin-composer-app-install.zip is an application bundle and is supposed to be dragged and dropped into your applications. If that doesn't work, I'll probably stop making those. Anyway, you'll want to run the JAR version of the app.

Download the skin_composer.jar file to your computer. Open a terminal, navigate to the folder, and run the following command: `java -jar skin_composer.jar`

**Comment by hermangh** [comment] 2017-02-13 04:36
Thanks for your prompt response. 
I've downloaded the version 8 jar file and tried with the command you suggested. I got below error message:

Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1384)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:425)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:372)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:107)
	at com.ray3k.skincomposer.desktop.DesktopLauncher.main(DesktopLauncher.java:50)
Caused by: java.lang.IllegalStateException: GLFW windows may only be created on the main thread and that thread must be the first thread in the process. Please run the JVM with -XstartOnFirstThread. For offscreen rendering, make sure another window toolkit (e.g. AWT or JavaFX) is initialized before GLFW.
	at org.lwjgl.glfw.EventLoop$OffScreen.<clinit>(EventLoop.java:38)
	... 5 more
AL lib: (EE) alc_cleanup: 1 device not closed

Any idea? Thanks in advance.

**Comment by hermangh** [comment] 2017-02-13 04:42
Oh! I got it now. I added the -XstartOnFirstThread in the command and it runs. Thanks.

**Comment by hermangh** [comment] 2017-02-13 05:24
... but now I have the skin composer started. When I clicked 'import', it does not ask me to save the project first and the finder brought up supposing to choose a skin but all skin json file is disabled and cannot be selected.

I also found that I cannot open any of the folder under the project settings. It just returns error.

Could it be I'm starting the skin composer with not adequate privilege? I'm using 'java -jar -XstartOnFirstThread skin_composer.jar' to start the program.

Any suggestion is welcomed. Thanks in advance.

**Comment by raeleus** [comment] 2017-02-13 13:53
I believe you are referring to the first tutorial video I made. The requirement to save before importing is no longer mandatory, however you can still go to File >> Save As before that step just in case.

The info.plist error is baffling to me. It must be related to the Tiny File Dialogs library.

Can you take a screenshot of the error when you try to open the folder? Also, be sure to extract the skins and associated files before proceeding.

**Comment by hermangh** [comment] 2017-02-13 14:14
The message is in the Terminal or Run Console in Android Studio. It is triggered when click on the import menu option and screenshot as below:

![screen shot 2017-02-13 at 10 09 02 pm](https://cloud.githubusercontent.com/assets/25733682/22886583/824f7d9c-f239-11e6-9c97-e37b53e39793.png)

**Comment by raeleus** [comment] 2017-02-13 14:43
Thank you for doing that. That clears up a few of my questions. I'll see if I can find a workaround today. I may ultimately have to find a way to run an emulator or something because I really am feeling in the dark here. Thanks for your feedback!

**Comment by hermangh** [comment] 2017-02-13 14:56
You're welcomed! Feel free to let me know if you need any further info or screenshots to help you understanding the problem I'm facing. Thanks.

**Comment by raeleus** [comment] 2017-02-13 20:47
I wrote a possible workaround available on master. Please give this a try. It should address the issue on all open dialogs. Basically I cleared the filter pattern on the dialog. You would just have to be sure to only open the appropriate file types (JSON files for import, SCMP files for open).
Can you also check if you can save the skin project as well? If not, I'll apply the change there too.

**Comment by hermangh** [comment] 2017-02-14 02:41
I've tried the version on master. It works for import, save, export. Thanks.

**Comment by raeleus** [comment] 2017-02-14 02:53
I'm glad to hear it. Thank you again for the report. I'll have another official release out this week.

**Comment by hermangh** [comment] 2017-02-14 05:12
That will be great! Thanks.

**Comment by destmaxi** [comment] 2018-03-02 08:39
I'm a mac user and I downloaded the .jar file and run it with java -jar -XstartOnFirstThread in the terminal but nothing happen ... Any idea ? 
I also tried to download the skin_composer-mac.zip file but the app open and close directly after without any error.

**Comment by raeleus** [comment] 2018-03-03 02:25
I added a new download "skin_composer_mac.jar" to version 16. Try that one. I'm shooting blindly here, but I hope that is a fix. I bought an old mac mini, but it's so old it doesn't run LibGDX apps. What a waste. Thanks for testing.

**Comment by destmaxi** [comment] 2018-03-04 00:13
Thanks for your prompt response,
It open a black window with "skin composer - New Project" as title. Once the window is open it's impossible to do anything (impossible to close it, ect...)

**Comment by raeleus** [comment] 2018-03-04 23:22
Sorry about that. Let's try one more change. Please download skin_composer_mac.jar from version 16 again and see if it works this time. Thanks for putting up with this trial and error.

**Comment by destmaxi** [comment] 2018-03-05 13:48
Thank you ! It work's perfectly.

**Comment by raeleus** [comment] 2018-03-05 17:09
Excellent! Thank you very much for your testing. I'll have proper (or my best approximation of proper) Mac releases in the future.

**Comment by raeleus** [comment] 2019-03-13 05:14
I'll mark this closed. With the next version I'll have proper Mac releases (hopefully) and wiki documentation to make it easier to get started.

**Closed by raeleus** 2019-03-13 05:14 UTC
