### ISSUE TITLE
There are some problems with the tooltip in the main interface, see the image below

### ISSUE THREAD

**Issue by ChinQingl** [raeleus/skin-composer#141] opened 2023-10-07 11:26 UTC
<img width="422" alt="tip" src="https://github.com/raeleus/skin-composer/assets/78594251/b34c96da-ca8e-479b-abb3-ee880bc88676">

**Comment by raeleus** [comment] 2024-03-04 15:40
Perhaps this was resolved with another fix. I cannot reproduce. Thanks.

**Closed by raeleus** 2024-03-04 15:40 UTC
