### ISSUE TITLE
Colors - RGB values displayed wrong

### ISSUE THREAD

**Issue by Grisgram** [raeleus/skin-composer#95] opened 2021-02-10 09:39 UTC
Hello Ray,

I found this while changing some colors.
In the picker, you show 180,180,180 as RGB values:
![image](https://user-images.githubusercontent.com/19487451/107491936-1bbe9380-6b8c-11eb-93a3-cd06240505fb.png)

but when I close the dialog, in the overview, you show 179,179,179
one of those starts counting with "0" :)
![image](https://user-images.githubusercontent.com/19487451/107492072-427cca00-6b8c-11eb-9a60-01f6e398e033.png)

**Comment by raeleus** [comment] 2021-02-10 15:01
Very good eye! You are very helpful. I'll try to focus on a release in the next few days. I got caught up on new features that are taking too long to implement.

**Comment by Grisgram** [comment] 2021-02-10 17:04
I am on my fork at this very moment - I take a look if I can solve it - I post here if I do a PR

cheers

**Comment by Grisgram** [comment] 2021-02-10 17:56
ok... the shown color that goes from 180 to 179 is stored in the skin file with a value of `0.70392156`  (8 digits, not 6, so it's a double)
When I multiply that with 255 I get 179,499999 which gets rounded to 179 instead of 180.

if it had only 6 digits, the value would be `0.703922` which gives 180,20 when multiplied with 255 and this would be the correct value.

I have seen that your spinner returns a double value but I couldn't figure out where the point is when this moves to the file to be saved.
But you should convert/cast it explicitly to float before saving - then the rounding/digit problem vanishes...

Let me know if my thoughts are right please :-)

**Comment by raeleus** [comment] 2021-02-10 18:00
Yeah, that's basically the cause from what I can remember without looking at the code. My number spinner class is kind of janky and it's on my short list for replacement. For solving the rounding issues.... I'm not sure if your solution will solve it for this one instance and remain an issue for others. The only safe way would be to store the colors as integers.

**Comment by Grisgram** [comment] 2021-02-10 18:07
but if you save it as int to the file, will that affect the loader in libgdx in any way?
hmm no... wrong thought... we are talking about the .scmp file here and not the exported skin.

The value in the skin must be correct, that's the most important part.
But from what i've seen, I fear I know not enough about the structures to fix that for you.
You have by far the better insights here - I leave this one to you, hope that's ok.
I try my luck again with the next bug :-)

cheers!

**Comment by raeleus** [comment] 2021-02-10 18:09
Thanks for looking! Hopefully it's just a few lines, but it might break backwards compatibility if I'm not careful

**Comment by raeleus** [comment] 2021-02-11 05:35
I'm having trouble reproducing this one. Can you reliably recreate this issue from a new, blank project?

**Comment by Grisgram** [comment] 2021-02-11 06:07
holy s***... you are right

in a new project this doesn't happen.
it's your grey color from the ShadeUi on your website --- I used this as base skin and enhanced/changed it for my project.
a new fresh color does it right.

hrmmm.... it happens with other colors of that skin too (the yellow and that pale blue for instance)
Maybe it's something with that skin - you created it with a very very old version? 

So... maybe this "bug" is just the need to update the skin template? :-)
Sorry for creating effort on your site --- I didn't expect the relation that it's originated from the skin

**Comment by raeleus** [comment] 2021-02-11 06:10
It would have to do with the accuracy of colors in exported skins. At least I know where to look now. I'll try tomorrow. Thanks!

**Comment by Grisgram** [comment] 2021-02-11 06:27
ok - sorry again 
if you find the time... contact me on discord (@Haerion) if you have 5 minutes to spare - I'd like to talk/write with you about an idea for the skin composer that might be a bit too much to write here on github - I would gladly help implementing it.
should be doable in less than a day but it's a new thing that would increase comfort a 1000 times and I need to know what you think... can it be done or not
cheers

**Comment by raeleus** [comment] 2021-02-16 03:10
It's just a matter of rounding the values passed to my spinners. This will be resolved with the next version. Thank you.

**Closed** 2021-06-05 13:50 UTC
