### ISSUE TITLE
Uncaught exception when saving project on Mac OS

### ISSUE THREAD

**Issue by fgermane** [raeleus/skin-composer#75] opened 2020-06-08 15:35 UTC
Hi, 
I am testing the last release of SkinComposer on my Mac, and I got the following error when I save the project.

My configuration : 
- Mac OS: Catalina 10.15.5
- Java:  14.0.1
- SkinComposer: 35

Here are the logs : 
2020-06-08 17:30:59.651 java[43690:1303750] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff31fdabe7 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6adb25bf objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff320033dc -[NSException raise] + 9
	3   AppKit                              0x00007fff2f201ddc -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 310
	4   AppKit                              0x00007fff2f2110ae -[NSThemeFrame _tileTitlebarAndRedisplay:] + 98
	5   AppKit                              0x00007fff2f224802 -[NSTitledFrame _titleDidChange] + 207
	6   AppKit                              0x00007fff2f2243a4 -[NSTitledFrame setTitle:] + 703
	7   AppKit                              0x00007fff2f224036 -[NSThemeFrame setTitle:] + 50
	8   AppKit                              0x00007fff2f223e32 -[NSWindow _dosetTitle:andDefeatWrap:] + 210
	9   libglfw.dylib                       0x000000011465f372 libglfw.dylib + 70514
	10  ???                                 0x000000011d092df0 0x0 + 4782108144
	11  ???                                 0x0000000115414ef3 0x0 + 4651568883
	12  ???                                 0x0000000115414ef3 0x0 + 4651568883
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by raeleus** [comment] 2020-06-08 15:53
I'm guessing it's some issue with TinyFileDialogs. Thanks for the report, I'll look into it.

**Comment by fgermane** [comment] 2020-06-09 07:43
Thanks a lot

**Comment by raeleus** [comment] 2020-06-11 02:47
This will be resolved in the next version... hopefully. I can't reproduce the issue, but I disabled all multi-threading for OSX, so it better not complain about that again.

**Closed by raeleus** 2020-06-11 02:47 UTC
