### ISSUE TITLE
SkinComposer slows down the system on Mac OS

### ISSUE THREAD

**Issue by fgermane** [raeleus/skin-composer#76] opened 2020-06-08 15:40 UTC
Hi,
When I launch the new version 35 of SkinComposer on my Mac OS Catalina 10.15.5, the whole system slows down. Mouse interaction are very slow...
However, CPU and memory do not seem to be at their limit.

Have you already noticed such slow-down on Mac OS ?

I don't if it may help: I am using Oracle JDK 14 : 
```
java version "14.0.1" 2020-04-14
Java(TM) SE Runtime Environment (build 14.0.1+7)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)
```

**Comment by raeleus** [comment] 2020-06-08 15:57
I haven't noticed anything, but that's because I'm used to my Mac being completely slow almost to the point of being unusable. It will continue to be my pain point for some time. JDK 14 is supposed to be fine. Can you try running it with the following paramaters?
```
java -jar -XstartOnFirstThread SkinComposer.jar
```
I included a hack to avoid having to use that, but I wonder if it's affecting performance. Specifying the flag should bypass the hack.

**Comment by fgermane** [comment] 2020-06-09 07:50
I have tested with -XstartOnFirstThread. But it does change the performances.
My Macbook is quite old (MacBook Pro Retina, 13 pouces, mi-2014 / 2,6 GHz Intel Core i5 double cœur). 
But it still performs quite well with any other applications. For example, I can easily run Android Studio and emulate a device in the meantime.
What is strange is that both CPU and memory seem to be ok... I have never seen such a behavior before. I will continue to observe and analyse it. I let you in touch.
Thanks

**Comment by MrStahlfelge** [comment] 2020-08-19 08:04
I tried on Catalina 10.15.6 with OpenJDK 11, no problems. Machine is from 2018 though.

**Comment by raeleus** [comment] 2020-08-20 06:14
I can't reproduce this either. Sorry, I can't see anything I'm doing would cause this problem besides the general incompatibilities of trying to run Java/LWJGL3/libGDX on the notriously challenging Mac platform. I'm going to close this for now. Please do report if you have anything new to add. Thank you.

**Closed by raeleus** 2020-08-20 06:14 UTC

**Comment by MrStahlfelge** [comment] 2020-09-07 14:43
May be related to libgdx/libgdx#5893
